### PR TITLE
EDIT: Alle Namen ausgeben!

### PR DESCRIPTION
**Pull request by mauricekoenig**
Gerne drüber sehen und schauen, ob es so angemessen ist.

Edit by Holger: blocked by #28

### CODE REVIEW

**Review by HolgerSin — APPROVED** [review]
Hatte noch die Ausgabefunktion in printToConsole umbenannt, zusammen mit dem Funktionsaufruf. Passt dann meinerseits!

**Review by HolgerSin — APPROVED** [review]
Kann ich das 2 mal approven?

**Comment by HolgerSin** [comment]
Hier ist ein merge conflict entstanden, würde ich wenn möglich gerne in Gruppe besprechen

blocked by #28

**Comment by HolgerSin** [comment]
:hourglass_flowing_sand: Alright! Looks like we need to wait for some *dependencies*:

* ComcaveTeamwork/CTP_01_TableReader#28

:bulb: Don't worry, I will continue watching the list above and keep this comment updated. To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!

**Comment by HolgerSin** [comment]
:hourglass_flowing_sand: Alright! Looks like we need to wait for some *dependencies*:

* ComcaveTeamwork/CTP_01_TableReader#28

:bulb: Don't worry, I will continue watching the list above and keep this comment updated. To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!

**Review by Hostmisha1 — APPROVED** [review]
Misha approved

**Review by danjan09 — DISMISSED** [review]
approve

**Comment by HolgerSin** [comment]
:tada: Great news! Looks like all the *dependencies* have been resolved:

* ~~ComcaveTeamwork/CTP_01_TableReader#28~~

:bulb: To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!

**Review by HolgerSin — APPROVED** [review]
+

**Review by RabuMia — APPROVED** [review]
me approves

**Pull request merged**
