### PR TITLE
Indu feature 63 datei auswählen

### PR DESCRIPTION
**Pull request by Indu1284**
fixes #

### CODE REVIEW

**Review by fatihkoeksal — DISMISSED** [review]
✔️

@HolgerSin FYI "i found out that its not possible to get full path of selected file using js because of security violation according to https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav

that because we didnt include your "show full path in console" demand.

**Comment by HolgerSin** [comment]
> ✔️
> 
> @HolgerSin FYI "i found out that its not possible to get full path of selected file using js because of security violation according to https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav
> 
> that because we didnt include your "show full path in console" demand.

OK, didn't know that actually...

**Review by mauricekoenig — APPROVED** [review]
Looking good guys - approved

**Review by HolgerSin — APPROVED** [review]

**Review by fatihkoeksal — APPROVED** [review]
✔️

**Review by RabuMia — APPROVED** [review]

**Pull request merged**
