### PR TITLE
Pull request for feature 38 -tableReader.js

### PR DESCRIPTION
**Pull request by Indu1284**
trying to add a Pushfunction.

### CODE REVIEW

**Review by RabuMia — DISMISSED** [review]
Indu-function is awesome :D

**Review by HolgerSin — APPROVED** [review]
looks good

**Review by mauricekoenig — APPROVED** [review]
Top.

**Review by fatihkoeksal — APPROVED** [review]
cool.

**Review by RabuMia — APPROVED** [review]

**Review by Hostmisha1 — APPROVED** [review]
läuft

**Pull request merged**
