### PR TITLE
buttonadterclick-deavtivated

### PR DESCRIPTION
**Pull request by nicopape**
line 34 added disabled function with true

### CODE REVIEW

**Review by HolgerSin — APPROVED** [review]
confirmed working

**Review by mauricekoenig — APPROVED** [review]
Worked auch für mich..

**Review by fatihkoeksal — APPROVED** [review]
worked.

**Review by RabuMia — APPROVED** [review]

**Review by Hostmisha1 — APPROVED** [review]
works

**Review by Indu1284 — APPROVED** [review]
Looks Good

**Pull request merged**
