### PR TITLE
Indu_Updating_tablereader

### PR DESCRIPTION
**Pull request by Indu1284**
Trying to add an ordered list in tablereader.html.

### CODE REVIEW

**Review by mauricekoenig — APPROVED** [review]
Looking good!

**Review by HolgerSin — APPROVED** [review]

**Review by nicopape — COMMENTED** [review]
Looks good. and its work

**Comment by HolgerSin** [comment]
@nicopape Bitte beim reviewen auch die Option "approve" auswählen wenn du mit den Änderungen einverstanden bist, siehe https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

**Review by RabuMia — DISMISSED** [review]

**Review by mauricekoenig — APPROVED** [review]

**Comment by HolgerSin** [comment]
Auto Comment: Merge Conflict in Pull Request detected by automation.

**Review by danjan09 — APPROVED** [review]

**Review by mauricekoenig — APPROVED** [review]

**Review by HolgerSin — APPROVED** [review]

**Review by danjan09 — APPROVED** [review]

**Review by RabuMia — APPROVED** [review]

**Pull request merged**
